#!/usr/bin/env node

const shell = require("shelljs");
const argv = require('yargs')
  .help('h')
  .alias('v', 'version')
  .alias('h', 'help')
  .alias('f', 'file')
  .describe('f', 'File name')
  .alias('t', 'type')
  .describe('t', 'Choice output format')
  .choices('t', ['json', 'xml'])
  .usage('Usage: emojidb -t type -f file')
  .epilog('copyright (C) 2019 phpz.xyz')
  .argv;

console.log(argv.name)

console.log(argv);
